import "tailwindcss/tailwind.css";
import type { Metadata } from "next";

export const metadata:Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const RootLayout: React.FCC = ({ children }) => {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
};
export default RootLayout;
